name: Build Samples

on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup emsdk
        uses: emscripten-core/setup-emsdk@v16
        with:
          version: 3.1.61

      - name: Install dependencies
        run: |
          sudo apt-get install python3-setuptools
          pip3 install --upgrade pip
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt --upgrade; fi

      - name: Build with Emscripten
        run: |
          export EMSCRIPTEN=$(dirname $(which emcc))
          python3 build-samples-web.py

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: build/site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
